'use client'

import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Check, ChevronDown, Search, RotateCcw, Save, LifeBuoy } from 'lucide-react'
import { Button, Card, PageHeader, Status } from './erp-shell'
import { getDefaultState, getStoredState, saveState, type AppState, type PreferencesState, type SettingsState, type UserProfile } from './profile-state'

function useAppState() {
  const [state, setState] = useState<AppState>(() => getDefaultState())
  useEffect(() => setState(getStoredState()), [])
  const update = (next: AppState) => { setState(next); saveState(next) }
  return { state, update }
}

const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="grid gap-1.5 text-xs font-semibold text-[#596a80]">{label}{children}</label>
const Input = (props: React.InputHTMLAttributes<HTMLInputElement>) => <input {...props} className="h-10 rounded-lg border border-[#dfe6ee] bg-white px-3 text-sm font-normal text-[#26364d] outline-none focus:border-[#3478d4]" />
const Select = (props: React.SelectHTMLAttributes<HTMLSelectElement>) => <select {...props} className="h-10 rounded-lg border border-[#dfe6ee] bg-white px-3 text-sm font-normal text-[#26364d] outline-none focus:border-[#3478d4]" />
const Toggle = ({ checked, onChange, label }: { checked: boolean; onChange: (value: boolean) => void; label: string }) => <label className="flex items-center justify-between gap-4 rounded-lg border border-[#eef1f5] px-4 py-3 text-sm text-[#526176]"><span>{label}</span><button type="button" aria-label={label} aria-pressed={checked} onClick={() => onChange(!checked)} className={`relative h-6 w-11 rounded-full transition-colors ${checked ? 'bg-[#216bd2]' : 'bg-[#dbe2eb]'}`}><span className={`absolute top-1 size-4 rounded-full bg-white transition-transform ${checked ? 'left-6' : 'left-1'}`} /></button></label>

export function ProfilePage() {
  const { state, update } = useAppState(); const [form, setForm] = useState<UserProfile>(state.user); const [saved, setSaved] = useState(false)
  useEffect(() => setForm(state.user), [state.user])
  const save = () => { update({ ...state, user: form }); setSaved(true); window.setTimeout(() => setSaved(false), 2500) }
  return <><PageHeader eyebrow="Account" title="Profile" description="Manage your personal information and account details." />{saved && <Notice text="Profile changes saved successfully." />}<Card className="max-w-4xl"><div className="flex flex-col gap-5 border-b border-[#eef1f5] p-5 sm:flex-row sm:items-center"><div className="flex size-16 items-center justify-center rounded-full bg-[#dbeafe] text-xl font-bold text-[#2161b5]">{form.name.split(' ').map(n => n[0]).join('').slice(0, 2)}</div><div><h2 className="text-base font-semibold text-[#253650]">{form.name}</h2><p className="mt-1 text-xs text-[#8491a5]">{form.role} · {form.email}</p></div><Status tone="green">{form.status}</Status></div><form onSubmit={e => { e.preventDefault(); save() }} className="grid gap-5 p-5 sm:grid-cols-2"><Field label="Full Name"><Input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required /></Field><Field label="Email"><Input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required /></Field><Field label="Role"><Input value={form.role} onChange={e => setForm({ ...form, role: e.target.value })} /></Field><Field label="Department"><Input value={form.department} onChange={e => setForm({ ...form, department: e.target.value })} /></Field><Field label="Phone"><Input type="tel" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></Field><Field label="Location"><Input value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} /></Field><div className="flex gap-2 sm:col-span-2"><Button type="submit"><Save size={14} /> Save Changes</Button><Button variant="secondary" onClick={() => setForm(state.user)}>Cancel</Button></div></form></Card></>
}

export function PreferencesPage() {
  const { state, update } = useAppState(); const [form, setForm] = useState<PreferencesState>(state.preferences); const [saved, setSaved] = useState(false)
  useEffect(() => setForm(state.preferences), [state.preferences])
  const save = () => { update({ ...state, preferences: form }); setSaved(true); window.setTimeout(() => setSaved(false), 2500) }
  const reset = () => { const preferences = getDefaultState().preferences; setForm(preferences); update({ ...state, preferences }) }
  return <><PageHeader eyebrow="Account" title="Preferences" description="Personalize your workspace experience." />{saved && <Notice text="Preferences saved successfully." />}<div className="grid max-w-5xl gap-4 lg:grid-cols-2"><Card className="p-5"><SectionTitle title="Appearance" /><Field label="Theme"><Select value={form.theme} onChange={e => setForm({ ...form, theme: e.target.value as PreferencesState['theme'] })}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></Select></Field><SectionTitle title="Notifications" /><div className="grid gap-2"><Toggle label="Email notifications" checked={form.emailNotifications} onChange={v => setForm({ ...form, emailNotifications: v })} /><Toggle label="In-app notifications" checked={form.inAppNotifications} onChange={v => setForm({ ...form, inAppNotifications: v })} /></div></Card><Card className="p-5"><SectionTitle title="Dashboard" /><div className="grid gap-4"><Field label="Default landing page"><Select value={form.defaultLandingPage} onChange={e => setForm({ ...form, defaultLandingPage: e.target.value })}><option value="/dashboard">Dashboard</option><option value="/finance/general-ledger">General Ledger</option><option value="/operations/inventory">Inventory</option></Select></Field><Field label="Default reporting period"><Select value={form.defaultReportingPeriod} onChange={e => setForm({ ...form, defaultReportingPeriod: e.target.value })}><option>This Month</option><option>Last Month</option><option>This Quarter</option><option>This Year</option></Select></Field><Field label="Currency"><Select value={form.currency} onChange={e => setForm({ ...form, currency: e.target.value })}><option>USD</option><option>INR</option><option>EUR</option></Select></Field><Field label="Date format"><Select value={form.dateFormat} onChange={e => setForm({ ...form, dateFormat: e.target.value })}><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></Select></Field></div></Card></div><div className="mt-4 flex gap-2"><Button onClick={save}><Save size={14} /> Save Preferences</Button><Button variant="secondary" onClick={reset}><RotateCcw size={14} /> Reset to Defaults</Button></div></>
}

export function SettingsPage() {
  const { state, update } = useAppState(); const [form, setForm] = useState<SettingsState>(state.settings); const [saved, setSaved] = useState(false)
  useEffect(() => setForm(state.settings), [state.settings])
  const save = () => { update({ ...state, settings: form }); setSaved(true); window.setTimeout(() => setSaved(false), 2500) }
  const reset = () => { const settings = getDefaultState().settings; setForm(settings); update({ ...state, settings }) }
  return <><PageHeader eyebrow="Administration" title="Settings" description="Configure workspace defaults for your ERP demo." />{saved && <Notice text="Workspace settings saved successfully." />}<div className="grid max-w-5xl gap-4 lg:grid-cols-2"><Card className="p-5"><SectionTitle title="General" /><div className="grid gap-4"><Field label="Workspace name"><Input value={form.workspaceName} onChange={e => setForm({ ...form, workspaceName: e.target.value })} /></Field><Field label="Fiscal year"><Input value={form.fiscalYear} onChange={e => setForm({ ...form, fiscalYear: e.target.value })} /></Field><Field label="Default currency"><Select value={form.defaultCurrency} onChange={e => setForm({ ...form, defaultCurrency: e.target.value })}><option>USD</option><option>INR</option><option>EUR</option></Select></Field><Field label="Timezone"><Select value={form.timezone} onChange={e => setForm({ ...form, timezone: e.target.value })}><option>Asia/Kolkata</option><option>America/New_York</option><option>Europe/London</option></Select></Field></div><SectionTitle title="Notifications" /><div className="grid gap-2"><Toggle label="Email notifications" checked={form.emailNotifications} onChange={v => setForm({ ...form, emailNotifications: v })} /><Toggle label="In-app notifications" checked={form.inAppNotifications} onChange={v => setForm({ ...form, inAppNotifications: v })} /></div></Card><Card className="p-5"><SectionTitle title="Security" /><div className="grid gap-4"><Field label="Session timeout"><Select value={String(form.sessionTimeout)} onChange={e => setForm({ ...form, sessionTimeout: Number(e.target.value) })}><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">60 minutes</option></Select></Field><Toggle label="Require confirmation for destructive actions" checked={form.requireConfirmation} onChange={v => setForm({ ...form, requireConfirmation: v })} /></div><SectionTitle title="Appearance" /><Field label="Theme"><Select value={form.theme} onChange={e => setForm({ ...form, theme: e.target.value as SettingsState['theme'] })}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></Select></Field><SectionTitle title="Data" /><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => window.alert('Demo workspace data exported.')}>Export workspace data</Button><Button variant="secondary" onClick={() => window.alert('Demo data reset.')}>Reset demo data</Button></div></Card></div><div className="mt-4 flex gap-2"><Button onClick={save}><Save size={14} /> Save Changes</Button><Button variant="secondary" onClick={reset}><RotateCcw size={14} /> Reset to Defaults</Button></div></>
}

const helpArticles = [{ title: 'Getting Started', body: 'Learn how to navigate the ERP, read your dashboard, and find key workspace actions.' }, { title: 'Finance', body: 'Understand General Ledger, Expenses, and Invoices.' }, { title: 'Operations', body: 'Understand Procurement, Inventory, and Sales.' }, { title: 'People', body: 'Manage employees, payroll, and users.' }, { title: 'Administration', body: 'Manage users, roles, preferences, and audit logs.' }]
const faqs = ['How do I create an invoice?', 'How do I create a purchase order?', 'How do I add an expense?', 'How do I add a product?', 'How do I invite a user?', 'Where can I view audit logs?']
export function HelpCenterPage() {
  const [query, setQuery] = useState(''); const [open, setOpen] = useState<string | null>(null); const filtered = useMemo(() => helpArticles.filter(a => `${a.title} ${a.body}`.toLowerCase().includes(query.toLowerCase())), [query])
  return <><PageHeader eyebrow="Support" title="Help Center" description="Find quick answers and guidance for your workspace." /><Card className="mb-4 flex max-w-5xl items-center gap-3 p-3"><Search size={17} className="text-[#8491a5]" /><input aria-label="Search help articles" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search help articles..." className="w-full bg-transparent text-sm outline-none" /></Card><div className="grid max-w-5xl gap-4 lg:grid-cols-[1fr_320px]"><Card className="p-5"><h2 className="text-sm font-semibold text-[#253650]">Quick Help</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{filtered.map(article => <div key={article.title} className="rounded-lg border border-[#eef1f5] p-4"><h3 className="text-sm font-semibold text-[#2869bb]">{article.title}</h3><p className="mt-2 text-xs leading-5 text-[#7a8798]">{article.body}</p></div>)}</div><h2 className="mt-7 text-sm font-semibold text-[#253650]">FAQ</h2><div className="mt-3 divide-y divide-[#eef1f5] rounded-lg border border-[#eef1f5]">{faqs.map(faq => <div key={faq}><button onClick={() => setOpen(open === faq ? null : faq)} className="flex w-full items-center justify-between px-4 py-3 text-left text-sm text-[#526176]"><span>{faq}</span><ChevronDown className={`transition-transform ${open === faq ? 'rotate-180' : ''}`} size={16} /></button>{open === faq && <p className="px-4 pb-4 text-xs leading-5 text-[#7a8798]">Open the relevant module from the sidebar, select the primary action, and complete the required fields. Your demo changes are kept in this browser.</p>}</div>)}</div></Card><Card className="h-fit p-5"><div className="flex size-10 items-center justify-center rounded-lg bg-[#eaf2ff] text-[#216bd2]"><LifeBuoy size={20} /></div><h2 className="mt-4 text-sm font-semibold text-[#253650]">Contact Support</h2><p className="mt-2 text-xs leading-5 text-[#7a8798]">Need more help? Our support team can guide you through your workspace.</p><p className="mt-4 text-sm font-semibold text-[#2869bb]">support@tensorik.in</p></Card></div></>
}
function SectionTitle({ title }: { title: string }) { return <h2 className="mb-4 mt-1 border-b border-[#eef1f5] pb-3 text-[10px] font-bold uppercase tracking-[0.14em] text-[#8491a5] first:mt-0">{title}</h2> }
function Notice({ text }: { text: string }) { return <div role="status" className="mb-4 flex items-center gap-2 rounded-lg border border-[#bfe6d3] bg-[#effaf4] px-4 py-3 text-xs font-medium text-[#21815b]"><Check size={15} />{text}</div> }

export function SignInPage() {
  const router = useRouter(); const { state, update } = useAppState(); const [email, setEmail] = useState('admin@tensorik.in'); const [password, setPassword] = useState(''); const [error, setError] = useState('')
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (email !== 'admin@tensorik.in' || password !== 'tensorik') { setError('Use the demo administrator credentials to continue.'); return }; update({ ...state, isSignedIn: true }); router.push('/dashboard') }
  return <div className="flex min-h-screen items-center justify-center bg-[#f6f8fb] p-4"><Card className="w-full max-w-md p-7"><div className="mb-8 text-center"><div className="mx-auto flex size-11 items-center justify-center rounded-lg bg-[#216bd2] text-white">T</div><p className="mt-4 text-[15px] font-bold tracking-tight text-[#152238]">TENSORIK</p><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[#8491a5]">Enterprise ERP</p><h1 className="mt-7 text-xl font-bold text-[#253650]">Sign in to your workspace</h1></div><form onSubmit={submit} className="grid gap-4"><Field label="Email"><Input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></Field><Field label="Password"><Input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></Field>{error && <p role="alert" className="text-xs text-[#c44747]">{error}</p>}<Button type="submit">Sign in</Button><p className="text-center text-[11px] text-[#8491a5]">Demo password: tensorik</p></form></Card></div>
}
