import { ArrowUpRight, ChevronDown, MoreHorizontal, Plus, ReceiptText, RefreshCw, ShoppingBag, WalletCards } from 'lucide-react'
import { Button, Card, ErpShell, PageHeader, Status } from '@/components/erp/erp-shell'
import { expenses, inventoryStatus, money, orders, products } from '@/components/erp/mock-data'

const chart = [42,55,48,63,58,71,66,82,75,88,79,94]
const revenue = orders.reduce((sum, order) => sum + order.amount, 0)
const expenseTotal = expenses.reduce((sum, expense) => sum + expense.amount, 0)

export default function Dashboard() {
  const lowStock = products.filter(product => inventoryStatus(product) !== 'In Stock')
  return <ErpShell><PageHeader eyebrow="Apex Manufacturing Group" title="Dashboard" description="Business overview and operational snapshot." action={<div className="flex gap-2"><Button variant="secondary"><RefreshCw size={14}/> Refresh</Button><Button><Plus size={15}/> New transaction</Button></div>}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Revenue" value={money(revenue)} change="12.8%" note="FY 2026 · loaded sales orders" icon={WalletCards} tone="blue"/><Metric label="Expenses" value={money(expenseTotal)} change="4.6%" note="Sep 2026 · recorded expenses" icon={ReceiptText} tone="amber" negative/><Metric label="Net profit" value={money(revenue-expenseTotal)} change="18.2%" note="FY 2026 demo contribution" icon={ArrowUpRight} tone="green"/><Metric label="Orders" value={String(orders.length)} change="8.4%" note="Sep 2026 · displayed records" icon={ShoppingBag} tone="violet"/></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.65fr_1fr]"><Card className="p-5"><div className="flex items-start justify-between"><div><h2 className="text-sm font-semibold text-[#253650]">Revenue & Expenses</h2><p className="mt-1 text-xs text-[#8995a6]">Monthly performance · FY 2026</p></div><button className="flex items-center gap-2 rounded-md border border-[#e3e8ef] px-2.5 py-1.5 text-xs text-[#637188]">This year <ChevronDown size={13}/></button></div><div className="mt-5 flex gap-5 text-xs"><span className="flex items-center gap-2 text-[#627187]"><i className="h-2 w-2 rounded-full bg-[#3478d4]"/> Revenue</span><span className="flex items-center gap-2 text-[#627187]"><i className="h-2 w-2 rounded-full bg-[#9bbbe8]"/> Expenses</span></div><div className="mt-5 flex h-[190px] items-end gap-2 border-b border-l border-[#e9edf2] px-3 pb-0 pt-6 sm:gap-4">{chart.map((height,i)=><div key={i} className="flex h-full flex-1 items-end gap-1"><div style={{height:`${height}%`}} className="w-1/2 rounded-t bg-[#3478d4]"/><div style={{height:`${Math.max(20,height-25)}%`}} className="w-1/2 rounded-t bg-[#b8cdea]"/></div>)}</div><div className="mt-2 flex justify-between pl-3 text-[10px] text-[#9aa6b6]"><span>Jan</span><span>Mar</span><span>May</span><span>Jul</span><span>Sep</span><span>Nov</span></div></Card><Card className="p-5"><div className="flex items-start justify-between"><div><h2 className="text-sm font-semibold text-[#253650]">Sales performance</h2><p className="mt-1 text-xs text-[#8995a6]">By customer · current demo records</p></div><MoreHorizontal size={18} className="text-[#94a0b1]"/></div><div className="mt-6 space-y-5">{orders.map(order=><div key={order.id}><div className="mb-2 flex justify-between text-xs"><span className="font-medium text-[#526176]">{order.customer}</span><span className="text-[#8591a2]">{money(order.amount)}</span></div><div className="h-1.5 rounded-full bg-[#edf1f5]"><div className="h-full rounded-full bg-[#3478d4]" style={{width:`${Math.min(100,Math.round(order.amount/revenue*100*2.2))}%`}}/></div></div>)}</div></Card></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.65fr_1fr]"><Card><div className="flex items-center justify-between border-b border-[#eef1f5] px-5 py-4"><div><h2 className="text-sm font-semibold text-[#253650]">Recent orders</h2><p className="mt-1 text-xs text-[#8995a6]">Latest sales activity across all channels</p></div><a href="/operations/sales" className="text-xs font-semibold text-[#216bd2]">View all</a></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="bg-[#fafbfd] text-[10px] uppercase tracking-[0.08em] text-[#9aa6b6]"><tr><th className="px-5 py-3">Order</th><th className="px-3 py-3">Customer</th><th className="px-3 py-3">Date</th><th className="px-3 py-3">Amount</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{orders.map(order=><tr key={order.id} className="border-t border-[#eef1f5]"><td className="px-5 py-3.5 font-semibold text-[#2869bb]">{order.id}</td><td className="px-3 py-3.5 font-medium text-[#526176]">{order.customer}</td><td className="px-3 py-3.5 text-[#8491a5]">{order.date}</td><td className="px-3 py-3.5 font-medium text-[#35465e]">{money(order.amount)}</td><td className="px-5 py-3.5"><Status tone={order.fulfillment==='Delivered'?'green':order.fulfillment==='Shipped'?'blue':'amber'}>{order.fulfillment}</Status></td></tr>)}</tbody></table></div></Card><Card><div className="border-b border-[#eef1f5] px-5 py-4"><h2 className="text-sm font-semibold text-[#253650]">Low stock alerts</h2><p className="mt-1 text-xs text-[#8995a6]">Derived from inventory reorder points</p></div><div className="divide-y divide-[#eef1f5]">{lowStock.map(product=><div key={product.sku} className="flex items-center justify-between px-5 py-4"><div><p className="text-xs font-semibold text-[#526176]">{product.name}</p><p className="mt-1 text-[11px] text-[#9aa6b6]">{product.sku}</p></div><span className="text-[11px] font-semibold text-[#b27713]">{product.quantity} units left</span></div>)}</div></Card></div></ErpShell>
}
function Metric({label,value,change,note,icon:Icon,tone,negative=false}:{label:string;value:string;change:string;note:string;icon:React.ElementType;tone:string;negative?:boolean}){const colors:Record<string,string>={blue:'bg-[#eaf2ff] text-[#216bd2]',amber:'bg-[#fff5dc] text-[#b27713]',green:'bg-[#e8f7f0] text-[#21815b]',violet:'bg-[#f1edff] text-[#7558c7]'};return <Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-[#7d899a]">{label}</p><p className="mt-2 text-2xl font-bold tracking-[-0.04em] text-[#1c2d45]">{value}</p></div><div className={`flex h-9 w-9 items-center justify-center rounded-lg ${colors[tone]}`}><Icon size={18}/></div></div><div className="mt-4 flex items-center gap-2 text-xs"><span className={negative?'font-semibold text-[#b27713]':'font-semibold text-[#21815b]'}>{negative?'↓':'↑'} {change}</span><span className="text-[#9aa6b6]">{note}</span></div></Card>}
